MCU = RP2040
BOOTLOADER = rp2040

BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE  = yes
EXTRAKEY_ENABLE  = yes
CONSOLE_ENABLE   = no
COMMAND_ENABLE   = no
NKRO_ENABLE      = yes

AUDIO_ENABLE     = no
RGBLIGHT_ENABLE  = no
RGB_MATRIX_ENABLE = no
BACKLIGHT_ENABLE = no
ENCODER_ENABLE   = no
LTO_ENABLE       = yes